# Generated by Django 2.1.7 on 2020-08-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycmprecord',
            old_name='cmp',
            new_name='current_mkt_price',
        ),
        migrations.RemoveField(
            model_name='company',
            name='cmp',
        ),
    ]
