# Generated by Django 2.1.7 on 2020-08-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200814_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycmprecord',
            old_name='current_mkt_price',
            new_name='cmp',
        ),
        migrations.AddField(
            model_name='company',
            name='cmp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
