# Generated by Django 2.0.2 on 2020-08-21 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocksDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointer', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Company')),
            ],
            options={
                'ordering': ['company', 'pointer'],
            },
        ),
        migrations.CreateModel(
            name='StocksDatabasePointer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointer', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stocksdatabase',
            unique_together={('company', 'pointer')},
        ),
    ]
